project_id = "rgaqvlsjaapjhlhevsrf"

[functions.enviar-avisos-agendamento]
verify_jwt = false

[functions.disparos-cron]
verify_jwt = false

[functions.formulario-whatsapp-notify]
verify_jwt = false

[functions.formulario-meta-conversion]
verify_jwt = false

[functions.process-reuniao-summary]
verify_jwt = false
