project_id = "rgaqvlsjaapjhlhevsrf"

[functions.enviar-avisos-agendamento]
verify_jwt = false

[functions.disparos-cron]
verify_jwt = false

[functions.formulario-whatsapp-notify]
verify_jwt = false

[functions.formulario-meta-conversion]
verify_jwt = false

[functions.process-reuniao-summary]
verify_jwt = false

[functions.google-calendar-cancel-event]
verify_jwt = false

[functions.google-calendar-update-event]
verify_jwt = false

[functions.enviar-aviso-reuniao-imediato]
verify_jwt = false

[functions.admin-keyword-handler]
verify_jwt = false

[functions.uazapi-admin-get-qrcode]
verify_jwt = false

[functions.uazapi-admin-create-instance]
verify_jwt = false

[functions.uazapi-test-connection]
verify_jwt = false

[functions.uazapi-check-status]
verify_jwt = false

[functions.uazapi-get-pairing-code]
verify_jwt = false

[functions.uazapi-set-webhook]
verify_jwt = false

[functions.admin-notification-create-instance]
verify_jwt = false
